### ISSUE TITLE
Check indicators types when adding

### ISSUE THREAD

**Issue by Te-k** [phishdetect/phishdetect-node#1]
There is currently no check on the type of indicator when a new indicator is added.

**Comment by botherder** [comment]
Do you mean to validate the format of the indicator in respect of the specified type, or to check whether the specified type is valid?

Currently there is no enforcement of particular indicator types. Should there be?

**Comment by Te-k** [comment]
Yes, I added indicators with a non-existing type by mistake the other day, it feels there should be an enforcement on types, at least to avoid mistakes on that side.

**Comment by botherder** [comment]
I don't think that should be possible though, and I was actually wrong. I'm not actually validating the type, but I'm sort of doing that anyway when preparing them for storage here:
https://github.com/phishdetect/phishdetect-node/blob/master/api_indicators.go#L35

As it is now, it shouldn't be possible to add indicators that are not "domain" or "email".
