### ISSUE TITLE
Add link on "Open Safely" analysis page for reporting to PhishDetect node

### ISSUE THREAD

**Issue by mfc** [phishdetect/phishdetect-node#3]
as part of further integrating functionality focused on reporting suspicious messages, in the analysis page of a link there should be a way to report it to the PhishDetect node for further analysis.

**Comment by botherder** [comment]
PhishDetect Node already provides a way to report suspicious links for further analysis (as currently possible from the extension's toolbar), so I just need to add a link inside the analysis results page.
Should this link only be provided when the analysis does not yield any suspicious result, or in every case?
