### ISSUE TITLE
Remove countdown and auto redirect on "Open safely" report page

### ISSUE THREAD

**Issue by mfc** [phishdetect/phishdetect-node#4]
this is feedback from CiviCERT meeting: having auto redirect to a suspicious page that has been submitted for analysis is problematic. now that we want to have functionality for submitting a suspicious email for further analysis, we should not be redirecting users automatically. instead we should [provide them with an ability to send the email/link/etc to the PhishDetect node for further analysis](https://github.com/phishdetect/phishdetect-node/issues/3), and the user can decide to continue to the link or not.

**Comment by botherder** [comment]
For clarity, the redirect only happens if nothing was detected as suspicious during the analysis. There is no countdown otherwise.
